### ISSUE TITLE
Error - "Data App is not accessible from the web"

### ISSUE THREAD

**Issue by adeimv** [european-dynamics-rnd/OneNet#12]
Hello,
The connector and communication with our docker worked perfectly before we did the upgrade. Now we are not able to communicate anymore. Has anyone else reported any issues to you? Were there any new ports introduced that now have to be opened? Has anything changed in the connector settings URLs? We also get prompted that some containers are "unhealthy". I am adding some of our error messages into this issue so you can see. 
Thank you in advance.

Additional: The Docker is on a Linux server for us.

![errors (2)](https://user-images.githubusercontent.com/115696714/204462139-88327931-cf54-4949-bf7b-28e8b690df14.png)
![errors (3)](https://user-images.githubusercontent.com/115696714/204462142-e1c8b08f-5fa5-4913-90cc-3de7f78fa0e9.png)
![errors (1)](https://user-images.githubusercontent.com/115696714/204462144-f5a94c40-ef1c-4314-8075-8701fa22c025.png)

**Comment by cchara63** [comment]
Hello we have some issues too. We want to know if Data App and ECC URL ports have been changed. Also for ecc URL we were referring to /data/ folder and ports 8889. While now we can still provide something we can't consume getting always an internal server error 500. Moreover while we have upgraded the docker files and even created a new folder while on the other PCs tests are passed it seems that inside the server docker we get the error Local API version is old where the server is running but we get OK communication for the clients.

**Comment by HeliasEurodyn** [comment]
Hello. 
All the ports are remaining the same, so you shouldnt have any issue with ports. 
Please check once more the Upgrade guide
https://github.com/european-dynamics-rnd/OneNet/wiki/OneNet-Upgrade-Guide-to-the-Latest-Version

Also consider checking the below aspects:

Firstly after loggin in on the Ui remember to clear the browser's cache by ```CTRL``` + ```SHIFT``` + ```R```   just to make sure that you received all the latest updates on your browsers. 

Next please look on the ```Connector Check``` section on your dashboard and let us know about the message that you receive. 

<img width="1087" alt="Στιγμιότυπο 2022-12-02, 12 16 13 μμ" src="https://user-images.githubusercontent.com/47740658/205270202-ebb0a027-14f5-4e71-875a-5addb8146869.png">

if you receive a message indicating that 

1. ```Local Application Not Found``` probably the local application is not running on your pc or the ```Local Api Url``` url is wrong on the ```Connector Settings``` menu on the Onenet Ui. You must check the Url (The http://localhost:30001/api is correct) OR restart the Local Application.

<img width="1095" alt="Στιγμιότυπο 2022-12-02, 12 19 10 μμ" src="https://user-images.githubusercontent.com/47740658/205271102-1c912954-6ac9-43d7-8e8c-6a92d8163534.png">

You can also download the latest version of the the Local Application from the ```Useful documents``` menu
![](https://raw.githubusercontent.com/european-dynamics-rnd/OneNet/main/usefuldocuments.jpg)

2. ```Local API Application Version is Old``` you probably missed the part of installing the new version of the Local Application on the client pc that you work on.
You can download it from the ```Useful documents```
![](https://raw.githubusercontent.com/european-dynamics-rnd/OneNet/main/usefuldocuments.jpg)

3. ```Data App cannot be found``` probably the docker installations are not running on the server OR the ```Data App``` url is wrong on the ```Connector Settings``` so the server is inaccessible. 

<img width="1095" alt="Στιγμιότυπο 2022-12-02, 12 19 10 μμ" src="https://user-images.githubusercontent.com/47740658/205271102-1c912954-6ac9-43d7-8e8c-6a92d8163534.png">

4. ```Data App cannot be accessed from the Web``` means that everythig is installed properly, but the Data App & Ecc url cannot be accessed on the web so you should contact your network administrator to expose those 2 on the internet. Also please consider that after exposing them you must provide the public urls to the onenet from the ```Connector Settings```.  As we checked right now most of the users did not finish with this step yet.  

5. ```Connection is established``` then everything should work fine.

You must be at least on the 4. ```Data App cannot be accessed from the Web``` step to be able to provide data on the onenet. Please provide us feedback about your current status on those and after we can procced and solve the other issues that you mention.

**Comment by HeliasEurodyn** [comment]
Hello barkalinowski.
On the pc where you run the application try to open this url on your browser
http://localhost:30001/api/onenet.html 

You should see this 
![local_app](https://user-images.githubusercontent.com/47740658/205628082-a98641bf-948b-4cf7-a00d-8ec8c53e1d79.png)

The Onenet Local Application must be the ```v1.3```. If you dont see this try downloading from 'Useful documents' and reruning the application. 

Please also consider that this ```Onenet Local Application``` is per client pc so consider doing this for all the pcs that you work on. Also remember to start the  ```Onenet Local Application``` when you restart your pc because it doesnt start automatically. If you want to automatically start this on every time that you restart your pc please let me know and I will send you the steps for this.  

If it doesnt work for any reason please mail me at ```helias.karagozidis@eurodyn.com``` and state your availability there to schedule a call and set it up together.

**Comment by adeimv** [comment]
Dear @HeliasEurodyn, thank you for your reply, we have no problems with the LocalApp, the connection is fine, but the Data App is still not accessible from the web. I have refreshed my browser multiple times and tested the ports 8889 and 8084 communication, and it works fine (over telnet and normal ping). Do you think reinstalling the docker completely would make thinks work? We have a Linux server for the docker, the Local App is running on our Windows PCs.

**Comment by HeliasEurodyn** [comment]
It is a network issue, I suggest to contact to your network administrator to regulate this. 

You can check this by the below steps:

I see on the system that your registered <b>Data App</b> url is ```<your Ip>:8889```
So if you open a browser from anywhere on the internet (Outside your Vpn) and type ```<your Ip>:8889/about/version``` you should be seeing this screen, which does not happen.

<img width="548" alt="Στιγμιότυπο 2022-12-06, 12 26 28 μμ" src="https://user-images.githubusercontent.com/47740658/205886669-52891990-a32d-4da6-8788-876e46cd1be5.png">

So it is clear that you need to expose it on the ineternet and you will finally get the ```Connection is established``` message.
Thank you.

**Comment by gtouloupos** [comment]
Dear Elias, 
We have gone throught your reply however we want to be more spesific now about the ports and issues we have too. 
We have updated everything as the documentantion and tryied both windows and linux server, and we can confirm the below: 
1. Our data app is accesible throught the internet, inside and outside our network. (through a public network)
![image](https://user-images.githubusercontent.com/50987007/205929469-7d477f6f-8c52-41c7-a1c5-c8b49a879513.png)
2. Connector Check option is working and shows everything is up
![image](https://user-images.githubusercontent.com/50987007/205930384-ca813c9b-8c74-46be-a185-6c29ddf660df.png)
3. In our configuration we have exposed the 2 ports through reverse proxy using HA proxy load balancer to archieve https communication. We can send the configuration part if needed of the front proxy server. We have not exposed the broker since as we understood this does not needed. So we use direct communication to internal ip for that. is that true? or does 1026 needs to be exposed too? We you are using a reverse proxy from an exposed server to the actual host machine which is reachable from local network for the 2 ports that need to be exposed. 
![image](https://user-images.githubusercontent.com/50987007/205931422-1e305d7e-3143-404a-a50e-38a7b1340f95.png)
4. We can normally upload-provide a file for example: 
![image](https://user-images.githubusercontent.com/50987007/205932099-f6f56db7-aa8f-4e35-b87d-fb6ca16036e5.png)
5. But we can never consume that file getting a server error 500 after a while. We are wondering if the problem is on reverse proxy configuration. What is that that may prevent us from consuming a file and is this completely impemented or did we missed something on the procudure of uploading a file and consuming it? 
![image](https://user-images.githubusercontent.com/50987007/205933119-f1ad27c1-84c3-44ba-a4c6-5d20dda965ac.png)

**Comment by HeliasEurodyn** [comment]
gtouloupos please try once more to Refresh the Application on the browser by ```CTRL``` + ```SHIFT``` + ```R``` & consume the file and let us know if it works.

**Comment by cchara63** [comment]
Dear HeliasEurodyn,

Regarding what you asked @gtouloupos to do, we did the Refresh of Application and the problem is still the same. We are doing all the steps for upload and download a document as we did with the previous application version (which occasionally has worked), but the issue of the new version is still the same (as @gtouloupos has already reported).  

Thank you,
Charalambos
UCY

**Comment by adeimv** [comment]
Dear @HeliasEurodyn, we have tried the "<your Ip>:8084" step and it works for us (outside of vpn). 
We have also tried reinstalling the docker one more time, but it still does not work for us. We are not able to connect. The local API works fine. Do you have any meeting option? To organize a call and check where the mistake is with our IT team?
Thank you in advance,
Amila (EIMV)
![about](https://user-images.githubusercontent.com/115696714/206456225-f1b92394-2584-44f2-9351-8f7539f41e32.PNG)

**Comment by adeimv** [comment]
Dear @HeliasEurodyn and other,
today I tried to access my connector settings and I got the message "forbidden".
![Capture](https://user-images.githubusercontent.com/115696714/207538455-e9b0b2dd-fb0e-45d5-a624-a51affb11b38.PNG)
